[package]
name = "components"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
gpui.workspace = true
primitives.workspace = true
theme.workspace = true
smallvec.workspace = true
serde.workspace = true
