[package]
name = "registry"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
components.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
