[package]
name = "gpui-cli"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[[bin]]
name = "gpui"
path = "src/main.rs"

[dependencies]
clap.workspace = true
registry.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
